#!/usr/bin/env python3
"""
Estimate the Lotka exponents alpha_0, alpha_1, alpha_2 of Egghe (2008)'s
successive-h-index model from this project's data, and the compound
exponents beta_1 = alpha_0*alpha_1 and beta_2 = alpha_0*alpha_1*alpha_2 that
h2_efficiency.py and h3_efficiency.py actually need (his eqs. 11 and 18).

Egghe's levels and where each exponent's tail shows up in our data:
  alpha_1 : Lotka tail of works_count (T, articles per author)      -- eq. 6
  alpha_2 : Lotka tail of author_count (S, authors per institution) -- eq. 13
  beta_1  : Lotka tail of h1 (h_index) across authors                -- eq. 7/8,  = alpha_0*alpha_1
  beta_2  : Lotka tail of h2 across institutions                     -- eq. 14/15, = alpha_0*alpha_1*alpha_2
  alpha_0 : Lotka tail of cited_by_count across articles -- eq. 3. Requires
            per-article citation counts (the OpenAlex works snapshot, not the
            authors snapshot the rest of this script reads), so it's only
            fit directly if data/interim/citation_sample.csv exists --
            produced by prefetch_citations.py, which samples a small spread
            of works partitions rather than the full ~725 GB snapshot (see
            its docstring for why that's enough data). If that file is
            absent, alpha_0 is left to the two indirect estimates below.
            Either way, it's also backed out two independent ways as a
            consistency check on the whole model: beta_1/alpha_1 and
            beta_2/(alpha_1*alpha_2) -- agreement between those and (if
            available) the direct fit is evidence the compounding-exponent
            model actually holds across levels, not just that each level
            individually looks Lotkaian.

Fitting method: discrete MLE (Clauset, Shalizi & Newman 2009) via the
`powerlaw` package, with x_min chosen automatically by minimizing the
Kolmogorov-Smirnov distance between empirical and fitted CDFs -- not an OLS
fit on a log-log rank-frequency plot, which is a known-biased estimator.
Egghe's densities (eqs. 3, 6, 13) are asserted to hold for the whole range
j >= 1, but real count data is typically power-law only above some
threshold, so x_min lets the data say where the tail actually starts. The
`alpha` returned by `powerlaw.Fit` uses the same density-exponent convention
as Egghe's, so it plugs directly into his formulas with no offset.

Each fit is otherwise unfiltered (no MIN_AUTHORS/MIN_INST-style cutoffs) so
the x_min search sees the full dynamic range; h2_efficiency.py and
h3_efficiency.py apply their own display cutoffs separately, after the
exponents are fixed.

works_count outliers: a first run of this script put alpha_1's x_min at 718
with only 171/2,000,000 tail points, and every one of the top-10 works_count
authors turned out to pair a huge count with a single-digit h_index (one has
works_count=278,862, h_index=1) -- see results/works_count_histogram.png
(generated by plot_works_count_hist.py). A real prolific individual has both
high works_count and high h_index; this pattern is the signature of an
OpenAlex author-disambiguation failure (a generic name or collaboration
byline absorbing many different people's publications into one author ID),
not genuine productivity. WORKS_COUNT_CAP excludes authors above a fixed
threshold before fitting alpha_1 only: works_count > 10,000 affects 46 of
27,083,177 authors (0.0002%), comfortably beyond any documented legitimate
individual publication count. The histogram itself doesn't show a clean
bimodal gap -- the tail thins out gradually, as expected for a real
power-law tail -- so this cap is justified by the implausibility of the
h_index/works_count pairing, not by a visible break in the distribution.
No such cap is applied to h1/h2/author_count: none of them showed this
pathology.

Runtime note: powerlaw's x_min search tries every distinct value in the data
as a candidate threshold, and each candidate re-scans the whole array (see
its functional.find_xmin) -- cost is roughly (# distinct values) x N, not N.
alpha_1 and beta_1 are fit on the ~17M-author-scale arrays and dominate this
script's runtime accordingly; alpha_2 and beta_2 (~20K institutions) are
fast. Rather than a progress bar for that O(N) rescan (which would need
patching powerlaw's internals), MAX_FIT_POINTS below subsamples the two
large arrays before fitting -- MLE tail estimation is data-efficient
(SE(alpha) ~ (alpha-1)/sqrt(n_tail), and n_tail is itself usually a small
fraction of n; the same argument justifies prefetch_citations.py's sample
size for alpha_0), so this costs negligible precision for a large runtime win.

Output: results/lotka_exponents.json

Usage:
  python3 prefetch_citations.py   # optional, enables the direct alpha_0 fit
  python3 estimate_alphas.py
"""

import json
import os
import time
import warnings

import duckdb
import numpy as np
import powerlaw

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INTERIM_DIR = os.path.join(ROOT_DIR, "data", "interim")
AUTHORS_CSV = os.path.join(INTERIM_DIR, "authors.csv")
H2_INST_CSV = os.path.join(INTERIM_DIR, "h2_by_institution.csv")
CITATIONS_CSV = os.path.join(INTERIM_DIR, "citation_sample.csv")  # optional, see prefetch_citations.py
OUT_JSON = os.path.join(ROOT_DIR, "results", "lotka_exponents.json")

MIN_POINTS = 50
MAX_FIT_POINTS = 2_000_000  # subsample larger arrays before fitting; see module docstring
WORKS_COUNT_CAP = 10_000  # exclude disambiguation-artifact authors before fitting alpha_1; see module docstring
RNG_SEED = 0


def subsample(values, label=""):
    """Randomly subsample `values` down to MAX_FIT_POINTS if larger.

    Deterministic (fixed seed) so re-running reproduces the same fit.
    """
    n = len(values)
    if n <= MAX_FIT_POINTS:
        return values, n
    rng = np.random.default_rng(RNG_SEED)
    sampled = rng.choice(values, size=MAX_FIT_POINTS, replace=False)
    print(f"    subsampling {n:,} -> {MAX_FIT_POINTS:,} points before fitting")
    return sampled, n


def fit_tail(values, label="", n_population=None):
    """Fit a discrete power-law tail to `values` (positive-integer counts).

    Returns alpha (Egghe's exponent for this level), xmin (tail threshold),
    n_tail/n_total (how much of the *fitted* data was used, i.e. after any
    subsampling), n_population (the true underlying population size, if
    different), D (the fit's KS statistic), and R_exp/p_exp (loglikelihood-
    ratio test of power-law vs. exponential -- R_exp > 0 & p_exp < 0.05
    favors power-law, R_exp < 0 & p_exp < 0.05 favors exponential, otherwise
    inconclusive).
    """
    values = np.asarray(values, dtype=float)
    values = values[values > 0]
    if len(values) < MIN_POINTS:
        raise ValueError(f"{label}: only {len(values)} positive values, too few to fit a tail")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fit = powerlaw.Fit(values, discrete=True, verbose=False)
        R_exp, p_exp = fit.distribution_compare(
            "power_law", "exponential", normalized_ratio=True
        )

    return {
        "label": label,
        "alpha": fit.power_law.alpha,
        "xmin": fit.power_law.xmin,
        "n_tail": int(np.sum(values >= fit.power_law.xmin)),
        "n_total": len(values),
        "n_population": n_population if n_population is not None else len(values),
        "D": fit.power_law.D,
        "R_exp": R_exp,
        "p_exp": p_exp,
    }


def summarize(r):
    if r["R_exp"] > 0 and r["p_exp"] < 0.05:
        verdict = "power-law favored over exponential"
    elif r["R_exp"] < 0 and r["p_exp"] < 0.05:
        verdict = "exponential favored over power-law"
    else:
        verdict = "inconclusive vs. exponential"
    sampled_note = (
        f" (sampled from {r['n_population']:,})" if r["n_population"] != r["n_total"] else ""
    )
    return (
        f"{r['label']}: alpha={r['alpha']:.3f}  xmin={r['xmin']:.0f}  "
        f"tail n={r['n_tail']:,}/{r['n_total']:,}{sampled_note} ({100*r['n_tail']/r['n_total']:.1f}%)  "
        f"D={r['D']:.4f}  [{verdict}, R={r['R_exp']:.2f} p={r['p_exp']:.3f}]"
    )


def main():
    for p in (AUTHORS_CSV, H2_INST_CSV):
        if not os.path.exists(p):
            raise SystemExit(f"ERROR: {p} not found.")

    con = duckdb.connect()
    con.execute("SET threads=4;")

    t0 = time.time()
    print("Loading h1 (h_index) and works_count from authors.csv...", end=" ", flush=True)
    h1_vals = con.execute(
        f"SELECT h_index FROM read_csv_auto('{AUTHORS_CSV}') WHERE h_index > 0"
    ).fetchnumpy()["h_index"]
    works_vals_all = con.execute(
        f"SELECT works_count FROM read_csv_auto('{AUTHORS_CSV}') WHERE works_count > 0"
    ).fetchnumpy()["works_count"]
    works_vals = works_vals_all[works_vals_all <= WORKS_COUNT_CAP]
    n_excluded = len(works_vals_all) - len(works_vals)
    print(f"{len(h1_vals):,} / {len(works_vals_all):,} rows ({time.time()-t0:.0f}s)")
    print(f"    excluding {n_excluded} authors with works_count > {WORKS_COUNT_CAP:,} "
          f"(disambiguation artifacts; see module docstring)")

    t0 = time.time()
    print("Loading h2 and author_count from h2_by_institution.csv...", end=" ", flush=True)
    h2_vals = con.execute(
        f"SELECT h2 FROM read_csv_auto('{H2_INST_CSV}') WHERE h2 > 0"
    ).fetchnumpy()["h2"]
    authorcount_vals = con.execute(
        f"SELECT author_count FROM read_csv_auto('{H2_INST_CSV}') WHERE author_count > 0"
    ).fetchnumpy()["author_count"]
    print(f"{len(h2_vals):,} / {len(authorcount_vals):,} rows ({time.time()-t0:.0f}s)")

    jobs = [
        ("alpha_1", works_vals, "alpha_1 (works_count / author, eq.6)"),
        ("alpha_2", authorcount_vals, "alpha_2 (author_count / institution, eq.13)"),
        ("beta_1", h1_vals, "beta_1 = alpha_0*alpha_1 (h1 / author, eq.7)"),
        ("beta_2", h2_vals, "beta_2 = alpha_0*alpha_1*alpha_2 (h2 / institution, eq.14)"),
    ]

    if os.path.exists(CITATIONS_CSV):
        print(f"Loading cited_by_count from {CITATIONS_CSV}...", end=" ", flush=True)
        t0 = time.time()
        citation_vals = con.execute(
            f"SELECT cited_by_count FROM read_csv_auto('{CITATIONS_CSV}') WHERE cited_by_count > 0"
        ).fetchnumpy()["cited_by_count"]
        print(f"{len(citation_vals):,} rows ({time.time()-t0:.0f}s)")
        jobs.append(("alpha_0", citation_vals, "alpha_0 (cited_by_count / article, eq.3)"))
    else:
        print(f"{CITATIONS_CSV} not found -- skipping direct alpha_0 fit "
              f"(run prefetch_citations.py to enable it). Falling back to indirect estimates.")

    print(f"\nFitting {len(jobs)} tail exponents (x_min search over each distribution)...")
    fits = {}
    for i, (key, values, label) in enumerate(jobs, 1):
        t0 = time.time()
        sampled, n_population = subsample(values, label)
        print(f"  [{i}/{len(jobs)}] {label}  (n={len(sampled):,})...", end=" ", flush=True)
        fits[key] = fit_tail(sampled, label, n_population=n_population)
        print(f"done in {time.time()-t0:.0f}s")
        print("      ", summarize(fits[key]))

    alpha_1 = fits["alpha_1"]["alpha"]
    alpha_2 = fits["alpha_2"]["alpha"]
    beta_1 = fits["beta_1"]["alpha"]
    beta_2 = fits["beta_2"]["alpha"]

    alpha_0_from_beta1 = beta_1 / alpha_1
    alpha_0_from_beta2 = beta_2 / (alpha_1 * alpha_2)
    beta_2_predicted = beta_1 * alpha_2

    print("\nDerived / consistency checks:")
    if "alpha_0" in fits:
        alpha_0_direct = fits["alpha_0"]["alpha"]
        print(f"  alpha_0 (direct fit, cited_by_count)     = {alpha_0_direct:.3f}")
    print(f"  alpha_0 (from beta_1/alpha_1)             = {alpha_0_from_beta1:.3f}")
    print(f"  alpha_0 (from beta_2/(alpha_1*alpha_2))   = {alpha_0_from_beta2:.3f}")
    print(
        f"  beta_2 observed vs. beta_1*alpha_2 predicted: "
        f"{beta_2:.3f} vs {beta_2_predicted:.3f} "
        f"({100*(beta_2-beta_2_predicted)/beta_2_predicted:+.1f}%)"
    )

    out = {
        "alpha_1": alpha_1,
        "alpha_2": alpha_2,
        "beta_1": beta_1,
        "beta_2": beta_2,
        "alpha_0_from_beta1": alpha_0_from_beta1,
        "alpha_0_from_beta2": alpha_0_from_beta2,
        "beta_2_predicted_from_beta1_alpha2": beta_2_predicted,
        "works_count_cap": WORKS_COUNT_CAP,
        "works_count_cap_excluded": n_excluded,
        "fits": fits,
    }
    if "alpha_0" in fits:
        out["alpha_0_direct"] = fits["alpha_0"]["alpha"]
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nWrote {OUT_JSON}")


if __name__ == "__main__":
    main()
